[package]
name = "auth"
version = "0.1.0"
authors = ["Martin KavÃ­k <martin@kavik.cz>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
gloo-console = "0.3.0"
gloo-net = "0.4.0"
gloo-storage = "0.3.0"
seed = { path = "../../", features = ["routing"] }
serde = "1.0.188"
