[package]
name = "page_trait"
version = "0.1.0"
authors = ["Martin KavÃ­k<martin@kavik.cz>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
gloo-console = "0.3.0"
seed = {path = "../../"}
