[package]
name = "fetch"
version = "0.1.0"
authors = ["TatriX <tatrics@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = {path = "../../"}
serde = { version = "1.0.137", features = ["derive"] }
futures = "0.3.21"
