[package]
name = "unsaved_changes"
version = "0.1.0"
authors = ["Martin KavÃ­k <martin@kavik.cz>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
gloo-console = "0.2.3"
gloo-storage = "0.2.2"
seed = {path = "../../"}
