[package]
name = "server"
version = "0.1.0"
authors = ["Your Name <email@address.com>"]
edition = "2021"

[dependencies]
tokio = { version = "1.8", features = ["full"] }  # sync with the one in `warp`
warp = "0.2"

shared = { path = "../shared" }
