[env]
# all workspace members can use this Makefile
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"
PORT = "8000"

# ---- BUILD & CREATE WASMS ----
[tasks.build]
description = "Build"
workspace = false
command = "cargo"
args = ["build"]

[tasks.build_release]
description = "Build, with the --release flag"
workspace = false
command = "cargo"
args = ["build", "--release"]

[tasks.create_wasm]
description = "Build with wasm-pack"
install_crate = "wasm-pack"
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "reports", "--out-dir", "../../pucks/static/pkg", "--dev"]


[tasks.create_wasm_release]
description = "Build with wasm-pack"
install_crate = "wasm-pack"
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "reports", "--out-dir", "../../pucks/static/pkg"]

[tasks.all]
description = "Build, and create wasms"
workspace = false
dependencies = ["build", "create_wasm"]

[tasks.all_release]
description = "Build, and create wasms, with the --release flag"
workspace = false
dependencies = ["build_release", "create_wasm_release"]

[tasks.serve]
description = "Start server"
install_crate = { crate_name = "microserver", binary = "microserver", test_arg = "-h" }
workspace = false
command = "microserver"
args = ["--port", "${PORT}"]




# Confusing name build with above
[tasks.build_reports]
description = ""
workspace = false
command = "cargo"
args = ["make", "--cwd", "./reports", "all"]

[tasks.build_me]
description = ""
workspace = false
command = "cargo"
args = ["make", "--cwd", "./me", "all"]

[tasks.build_all]
description = "Build, and create wasms"
workspace = false
dependencies = ["build_reports", "build_me"]



# ---- TEST ----

[tasks.test]
description = "Run tests. Ex: 'cargo make test firefox'. Test envs: [chrome, firefox, safari]"
clear = true
workspace = false
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["test", "--${@}"]

[tasks.test_release]
extend = "test"
description = "Run tests in release mode. Ex: 'cargo make test firefox'. Test envs: [chrome, firefox, safari]"
args = ["test", "--${@}", "--release"]

[tasks.test_h]
description = "Run headless tests. Ex: 'cargo make test_h firefox'. Test envs: [chrome, firefox, safari]"
extend = "test"
args = ["test", "--headless", "--${@}"]

[tasks.test_h_release]
extend = "test_h"
description = "Run headless tests in release mode. Ex: 'cargo make test_h firefox'. Test envs: [chrome, firefox, safari]"
args = ["test", "--headless", "--${@}", "--release"]

[tasks.test_one]
description = "Run Seed's tests. Ex: 'cargo make test firefox'. Test envs: [chrome, firefox, safari]"
clear = true
workspace = false
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["test", "--firefox", "--headless", "--", "--lib", "${@}"]